twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
        '%kernel.project_dir%/templates': ~
        '%kernel.project_dir%/templates/bundles/TwigBundle/Exception': TwigBundle/Exception


when@test:
    twig:
        strict_variables: true
